gdjs.Untitled_32sceneCode = {};
gdjs.Untitled_32sceneCode.localVariables = [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter12Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter12Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter3Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter3Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter2Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter2Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter1Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter1Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter11Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter11Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter10Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter10Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter5Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter5Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter4Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter4Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter6Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter6Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter9Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter9Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter7Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter7Objects2= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter8Objects1= [];
gdjs.Untitled_32sceneCode.GDFemaleCharacter8Objects2= [];
gdjs.Untitled_32sceneCode.GDzeusObjects1= [];
gdjs.Untitled_32sceneCode.GDzeusObjects2= [];
gdjs.Untitled_32sceneCode.GDkidObjects1= [];
gdjs.Untitled_32sceneCode.GDkidObjects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter4Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter4Objects2= [];
gdjs.Untitled_32sceneCode.GDzden_95283k_9595poloreichObjects1= [];
gdjs.Untitled_32sceneCode.GDzden_95283k_9595poloreichObjects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter11Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter11Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter7Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter7Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter1Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter1Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter3Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter3Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter9Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter9Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter6Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter6Objects2= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter8Objects1= [];
gdjs.Untitled_32sceneCode.GDMaleCharacter8Objects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone1Objects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone1Objects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone2Objects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone2Objects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardBackgroundObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardBackgroundObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone3Objects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone3Objects2= [];
gdjs.Untitled_32sceneCode.GDArrowSignObjects1= [];
gdjs.Untitled_32sceneCode.GDArrowSignObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone4Objects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardBone4Objects2= [];
gdjs.Untitled_32sceneCode.GDCrateObjects1= [];
gdjs.Untitled_32sceneCode.GDCrateObjects2= [];
gdjs.Untitled_32sceneCode.GDSignObjects1= [];
gdjs.Untitled_32sceneCode.GDSignObjects2= [];
gdjs.Untitled_32sceneCode.GDTombStone1Objects1= [];
gdjs.Untitled_32sceneCode.GDTombStone1Objects2= [];
gdjs.Untitled_32sceneCode.GDSkeletonObjects1= [];
gdjs.Untitled_32sceneCode.GDSkeletonObjects2= [];
gdjs.Untitled_32sceneCode.GDTombStone2Objects1= [];
gdjs.Untitled_32sceneCode.GDTombStone2Objects2= [];
gdjs.Untitled_32sceneCode.GDBush1Objects1= [];
gdjs.Untitled_32sceneCode.GDBush1Objects2= [];
gdjs.Untitled_32sceneCode.GDTreeObjects1= [];
gdjs.Untitled_32sceneCode.GDTreeObjects2= [];
gdjs.Untitled_32sceneCode.GDDeadBushObjects1= [];
gdjs.Untitled_32sceneCode.GDDeadBushObjects2= [];
gdjs.Untitled_32sceneCode.GDBush2Objects1= [];
gdjs.Untitled_32sceneCode.GDBush2Objects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerRightObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerRightObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileTopLeftCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileTopLeftCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileTopRightCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileTopRightCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileWaterObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileWaterObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformCenterObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformCenterObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerBackgroundObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerBackgroundObjects2= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformRightObjects1= [];
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformRightObjects2= [];
gdjs.Untitled_32sceneCode.GDCrate2Objects1= [];
gdjs.Untitled_32sceneCode.GDCrate2Objects2= [];
gdjs.Untitled_32sceneCode.GDSign2Objects1= [];
gdjs.Untitled_32sceneCode.GDSign2Objects2= [];
gdjs.Untitled_32sceneCode.GDBush3Objects1= [];
gdjs.Untitled_32sceneCode.GDBush3Objects2= [];
gdjs.Untitled_32sceneCode.GDBush4Objects1= [];
gdjs.Untitled_32sceneCode.GDBush4Objects2= [];
gdjs.Untitled_32sceneCode.GDBush5Objects1= [];
gdjs.Untitled_32sceneCode.GDBush5Objects2= [];
gdjs.Untitled_32sceneCode.GDSignArrowObjects1= [];
gdjs.Untitled_32sceneCode.GDSignArrowObjects2= [];
gdjs.Untitled_32sceneCode.GDMushroom1Objects1= [];
gdjs.Untitled_32sceneCode.GDMushroom1Objects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileWaterWavesObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileWaterWavesObjects2= [];
gdjs.Untitled_32sceneCode.GDTree1Objects1= [];
gdjs.Untitled_32sceneCode.GDTree1Objects2= [];
gdjs.Untitled_32sceneCode.GDBush6Objects1= [];
gdjs.Untitled_32sceneCode.GDBush6Objects2= [];
gdjs.Untitled_32sceneCode.GDTree2Objects1= [];
gdjs.Untitled_32sceneCode.GDTree2Objects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileObjects2= [];
gdjs.Untitled_32sceneCode.GDTree3Objects1= [];
gdjs.Untitled_32sceneCode.GDTree3Objects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerRightObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerRightObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformRightObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformRightObjects2= [];
gdjs.Untitled_32sceneCode.GDMushroom2Objects1= [];
gdjs.Untitled_32sceneCode.GDMushroom2Objects2= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformCenterObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTilePlatformCenterObjects2= [];
gdjs.Untitled_32sceneCode.GDStoneObjects1= [];
gdjs.Untitled_32sceneCode.GDStoneObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileWaterObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileWaterObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterBackgroundObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterBackgroundObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileTopRightCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileTopRightCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDSummerTileTopLeftCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDSummerTileTopLeftCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDCrate3Objects1= [];
gdjs.Untitled_32sceneCode.GDCrate3Objects2= [];
gdjs.Untitled_32sceneCode.GDCrystalObjects1= [];
gdjs.Untitled_32sceneCode.GDCrystalObjects2= [];
gdjs.Untitled_32sceneCode.GDIglooObjects1= [];
gdjs.Untitled_32sceneCode.GDIglooObjects2= [];
gdjs.Untitled_32sceneCode.GDSign3Objects1= [];
gdjs.Untitled_32sceneCode.GDSign3Objects2= [];
gdjs.Untitled_32sceneCode.GDSignArrow2Objects1= [];
gdjs.Untitled_32sceneCode.GDSignArrow2Objects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileWaterWavesObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileWaterWavesObjects2= [];
gdjs.Untitled_32sceneCode.GDSnowManObjects1= [];
gdjs.Untitled_32sceneCode.GDSnowManObjects2= [];
gdjs.Untitled_32sceneCode.GDIceBoxObjects1= [];
gdjs.Untitled_32sceneCode.GDIceBoxObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileObjects2= [];
gdjs.Untitled_32sceneCode.GDTree4Objects1= [];
gdjs.Untitled_32sceneCode.GDTree4Objects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerRightObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerRightObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformRightObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformRightObjects2= [];
gdjs.Untitled_32sceneCode.GDTree5Objects1= [];
gdjs.Untitled_32sceneCode.GDTree5Objects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileTopRightCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileTopRightCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformCenterObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTilePlatformCenterObjects2= [];
gdjs.Untitled_32sceneCode.GDStone2Objects1= [];
gdjs.Untitled_32sceneCode.GDStone2Objects2= [];
gdjs.Untitled_32sceneCode.GDDesertBackgroundObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertBackgroundObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTileObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTileObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDWinterTileTopLeftCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDWinterTileTopLeftCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerRightObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerRightObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformLeftObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformLeftObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformRightObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformRightObjects2= [];
gdjs.Untitled_32sceneCode.GDk_95225menObjects1= [];
gdjs.Untitled_32sceneCode.GDk_95225menObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTileTopRightCornerObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTileTopRightCornerObjects2= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformCenterObjects1= [];
gdjs.Untitled_32sceneCode.GDDesertTilePlatformCenterObjects2= [];
gdjs.Untitled_32sceneCode.GDCrate4Objects1= [];
gdjs.Untitled_32sceneCode.GDCrate4Objects2= [];
gdjs.Untitled_32sceneCode.GDSign4Objects1= [];
gdjs.Untitled_32sceneCode.GDSign4Objects2= [];
gdjs.Untitled_32sceneCode.GDSignArrow3Objects1= [];
gdjs.Untitled_32sceneCode.GDSignArrow3Objects2= [];
gdjs.Untitled_32sceneCode.GDSkeleton2Objects1= [];
gdjs.Untitled_32sceneCode.GDSkeleton2Objects2= [];
gdjs.Untitled_32sceneCode.GDBush7Objects1= [];
gdjs.Untitled_32sceneCode.GDBush7Objects2= [];
gdjs.Untitled_32sceneCode.GDCactus1Objects1= [];
gdjs.Untitled_32sceneCode.GDCactus1Objects2= [];
gdjs.Untitled_32sceneCode.GDBush8Objects1= [];
gdjs.Untitled_32sceneCode.GDBush8Objects2= [];
gdjs.Untitled_32sceneCode.GDCactus2Objects1= [];
gdjs.Untitled_32sceneCode.GDCactus2Objects2= [];
gdjs.Untitled_32sceneCode.GDCactus3Objects1= [];
gdjs.Untitled_32sceneCode.GDCactus3Objects2= [];
gdjs.Untitled_32sceneCode.GDGrass1Objects1= [];
gdjs.Untitled_32sceneCode.GDGrass1Objects2= [];
gdjs.Untitled_32sceneCode.GDGrass2Objects1= [];
gdjs.Untitled_32sceneCode.GDGrass2Objects2= [];
gdjs.Untitled_32sceneCode.GDStone3Objects1= [];
gdjs.Untitled_32sceneCode.GDStone3Objects2= [];
gdjs.Untitled_32sceneCode.GDTree6Objects1= [];
gdjs.Untitled_32sceneCode.GDTree6Objects2= [];
gdjs.Untitled_32sceneCode.GDStoneBlockObjects1= [];
gdjs.Untitled_32sceneCode.GDStoneBlockObjects2= [];
gdjs.Untitled_32sceneCode.GDCarGirlBodyObjects1= [];
gdjs.Untitled_32sceneCode.GDCarGirlBodyObjects2= [];
gdjs.Untitled_32sceneCode.GDCarGirlHeadObjects1= [];
gdjs.Untitled_32sceneCode.GDCarGirlHeadObjects2= [];
gdjs.Untitled_32sceneCode.GDOrcBodyObjects1= [];
gdjs.Untitled_32sceneCode.GDOrcBodyObjects2= [];
gdjs.Untitled_32sceneCode.GDOrcHeadObjects1= [];
gdjs.Untitled_32sceneCode.GDOrcHeadObjects2= [];
gdjs.Untitled_32sceneCode.GDOrcWheelObjects1= [];
gdjs.Untitled_32sceneCode.GDOrcWheelObjects2= [];
gdjs.Untitled_32sceneCode.GDTruckerBodyObjects1= [];
gdjs.Untitled_32sceneCode.GDTruckerBodyObjects2= [];
gdjs.Untitled_32sceneCode.GDTruckerHeadObjects1= [];
gdjs.Untitled_32sceneCode.GDTruckerHeadObjects2= [];
gdjs.Untitled_32sceneCode.GDTruckerWheelObjects1= [];
gdjs.Untitled_32sceneCode.GDTruckerWheelObjects2= [];
gdjs.Untitled_32sceneCode.GDAdventureBoyObjects1= [];
gdjs.Untitled_32sceneCode.GDAdventureBoyObjects2= [];
gdjs.Untitled_32sceneCode.GDCarGirlWheelObjects1= [];
gdjs.Untitled_32sceneCode.GDCarGirlWheelObjects2= [];
gdjs.Untitled_32sceneCode.GDAdventureGirlObjects1= [];
gdjs.Untitled_32sceneCode.GDAdventureGirlObjects2= [];
gdjs.Untitled_32sceneCode.GDCatObjects1= [];
gdjs.Untitled_32sceneCode.GDCatObjects2= [];
gdjs.Untitled_32sceneCode.GDCuteGirlObjects1= [];
gdjs.Untitled_32sceneCode.GDCuteGirlObjects2= [];
gdjs.Untitled_32sceneCode.GDDinoObjects1= [];
gdjs.Untitled_32sceneCode.GDDinoObjects2= [];
gdjs.Untitled_32sceneCode.GDDogObjects1= [];
gdjs.Untitled_32sceneCode.GDDogObjects2= [];
gdjs.Untitled_32sceneCode.GDFlatBoyObjects1= [];
gdjs.Untitled_32sceneCode.GDFlatBoyObjects2= [];
gdjs.Untitled_32sceneCode.GDJackObjects1= [];
gdjs.Untitled_32sceneCode.GDJackObjects2= [];
gdjs.Untitled_32sceneCode.GDKnightObjects1= [];
gdjs.Untitled_32sceneCode.GDKnightObjects2= [];
gdjs.Untitled_32sceneCode.GDKunaiObjects1= [];
gdjs.Untitled_32sceneCode.GDKunaiObjects2= [];
gdjs.Untitled_32sceneCode.GDKunai2Objects1= [];
gdjs.Untitled_32sceneCode.GDKunai2Objects2= [];
gdjs.Untitled_32sceneCode.GDNinjaBoyObjects1= [];
gdjs.Untitled_32sceneCode.GDNinjaBoyObjects2= [];
gdjs.Untitled_32sceneCode.GDNinjaGirlObjects1= [];
gdjs.Untitled_32sceneCode.GDNinjaGirlObjects2= [];
gdjs.Untitled_32sceneCode.GDRedHatBoyObjects1= [];
gdjs.Untitled_32sceneCode.GDRedHatBoyObjects2= [];
gdjs.Untitled_32sceneCode.GDSantaObjects1= [];
gdjs.Untitled_32sceneCode.GDSantaObjects2= [];
gdjs.Untitled_32sceneCode.GDZombieBoyObjects1= [];
gdjs.Untitled_32sceneCode.GDZombieBoyObjects2= [];
gdjs.Untitled_32sceneCode.GDZombieGirlObjects1= [];
gdjs.Untitled_32sceneCode.GDZombieGirlObjects2= [];
gdjs.Untitled_32sceneCode.GDRobotObjects1= [];
gdjs.Untitled_32sceneCode.GDRobotObjects2= [];
gdjs.Untitled_32sceneCode.GDBulletObjects1= [];
gdjs.Untitled_32sceneCode.GDBulletObjects2= [];
gdjs.Untitled_32sceneCode.GDMuzzleObjects1= [];
gdjs.Untitled_32sceneCode.GDMuzzleObjects2= [];
gdjs.Untitled_32sceneCode.GDNewSpriteObjects1= [];
gdjs.Untitled_32sceneCode.GDNewSpriteObjects2= [];
gdjs.Untitled_32sceneCode.GDRockHeadObjects1= [];
gdjs.Untitled_32sceneCode.GDRockHeadObjects2= [];
gdjs.Untitled_32sceneCode.GDtrggerObjects1= [];
gdjs.Untitled_32sceneCode.GDtrggerObjects2= [];
gdjs.Untitled_32sceneCode.GDbafObjects1= [];
gdjs.Untitled_32sceneCode.GDbafObjects2= [];


gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects = Hashtable.newFrom({"zeus": gdjs.Untitled_32sceneCode.GDzeusObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDSkeletonObjects1Objects = Hashtable.newFrom({"Skeleton": gdjs.Untitled_32sceneCode.GDSkeletonObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects = Hashtable.newFrom({"zeus": gdjs.Untitled_32sceneCode.GDzeusObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDNewSpriteObjects1Objects = Hashtable.newFrom({"NewSprite": gdjs.Untitled_32sceneCode.GDNewSpriteObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects = Hashtable.newFrom({"zeus": gdjs.Untitled_32sceneCode.GDzeusObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDRockHeadObjects1Objects = Hashtable.newFrom({"RockHead": gdjs.Untitled_32sceneCode.GDRockHeadObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects = Hashtable.newFrom({"zeus": gdjs.Untitled_32sceneCode.GDzeusObjects1});
gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDtrggerObjects1Objects = Hashtable.newFrom({"trgger": gdjs.Untitled_32sceneCode.GDtrggerObjects1});
gdjs.Untitled_32sceneCode.eventsList0 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.runtimeScene.sceneJustBegins(runtimeScene);
if (isConditionTrue_0) {
}

}


{

gdjs.copyArray(runtimeScene.getObjects("Skeleton"), gdjs.Untitled_32sceneCode.GDSkeletonObjects1);
gdjs.copyArray(runtimeScene.getObjects("zeus"), gdjs.Untitled_32sceneCode.GDzeusObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.object.hitBoxesCollisionTest(gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects, gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDSkeletonObjects1Objects, false, runtimeScene, false);
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "Untitled scene", false);
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("NewSprite"), gdjs.Untitled_32sceneCode.GDNewSpriteObjects1);
gdjs.copyArray(runtimeScene.getObjects("zeus"), gdjs.Untitled_32sceneCode.GDzeusObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.object.hitBoxesCollisionTest(gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects, gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDNewSpriteObjects1Objects, false, runtimeScene, false);
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "Untitled scene", false);
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("RockHead"), gdjs.Untitled_32sceneCode.GDRockHeadObjects1);
gdjs.copyArray(runtimeScene.getObjects("zeus"), gdjs.Untitled_32sceneCode.GDzeusObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.object.hitBoxesCollisionTest(gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects, gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDRockHeadObjects1Objects, false, runtimeScene, false);
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "Untitled scene", false);
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("trgger"), gdjs.Untitled_32sceneCode.GDtrggerObjects1);
gdjs.copyArray(runtimeScene.getObjects("zeus"), gdjs.Untitled_32sceneCode.GDzeusObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.object.hitBoxesCollisionTest(gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDzeusObjects1Objects, gdjs.Untitled_32sceneCode.mapOfGDgdjs_9546Untitled_959532sceneCode_9546GDtrggerObjects1Objects, false, runtimeScene, false);
if (isConditionTrue_0) {
gdjs.copyArray(runtimeScene.getObjects("baf"), gdjs.Untitled_32sceneCode.GDbafObjects1);
/* Reuse gdjs.Untitled_32sceneCode.GDzeusObjects1 */
{for(var i = 0, len = gdjs.Untitled_32sceneCode.GDzeusObjects1.length ;i < len;++i) {
    gdjs.Untitled_32sceneCode.GDzeusObjects1[i].setPosition((( gdjs.Untitled_32sceneCode.GDbafObjects1.length === 0 ) ? 0 :gdjs.Untitled_32sceneCode.GDbafObjects1[0].getPointX("")),(( gdjs.Untitled_32sceneCode.GDbafObjects1.length === 0 ) ? 0 :gdjs.Untitled_32sceneCode.GDbafObjects1[0].getPointY("")));
}
}}

}


};

gdjs.Untitled_32sceneCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.Untitled_32sceneCode.GDFemaleCharacter12Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter12Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter11Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter11Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter10Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter10Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter5Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter5Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter6Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter6Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter9Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter9Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter7Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter7Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter8Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDFemaleCharacter8Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDzeusObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDzeusObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDkidObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDkidObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDzden_95283k_9595poloreichObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDzden_95283k_9595poloreichObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter11Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter11Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter7Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter7Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter9Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter9Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter6Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter6Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter8Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMaleCharacter8Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBackgroundObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBackgroundObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDArrowSignObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDArrowSignObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardBone4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDCrateObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCrateObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSignObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSignObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTombStone1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTombStone1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSkeletonObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSkeletonObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTombStone2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTombStone2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDTreeObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDTreeObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDeadBushObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDeadBushObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileTopLeftCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileTopLeftCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileTopRightCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileTopRightCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileWaterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileWaterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTileDirtCornerLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformCenterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformCenterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerBackgroundObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerBackgroundObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDGraveyardTilePlatformRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCrate2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCrate2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSign2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSign2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush5Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush5Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrowObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrowObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDMushroom1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMushroom1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileWaterWavesObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileWaterWavesObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush6Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush6Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileDirtCornerRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDMushroom2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDMushroom2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformCenterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTilePlatformCenterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDStoneObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDStoneObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileWaterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileWaterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterBackgroundObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterBackgroundObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileTopRightCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileTopRightCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileTopLeftCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSummerTileTopLeftCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCrate3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCrate3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDCrystalObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCrystalObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDIglooObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDIglooObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSign3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSign3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrow2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrow2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileWaterWavesObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileWaterWavesObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSnowManObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSnowManObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDIceBoxObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDIceBoxObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileDirtCornerRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree5Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree5Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileTopRightCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileTopRightCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformCenterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTilePlatformCenterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDStone2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDStone2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertBackgroundObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertBackgroundObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileTopLeftCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDWinterTileTopLeftCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileDirtCornerRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformLeftObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformLeftObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformRightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformRightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDk_95225menObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDk_95225menObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileTopRightCornerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTileTopRightCornerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformCenterObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDesertTilePlatformCenterObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCrate4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCrate4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSign4Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSign4Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrow3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSignArrow3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDSkeleton2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDSkeleton2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush7Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush7Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDCactus1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCactus1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDBush8Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDBush8Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDCactus2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCactus2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDCactus3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDCactus3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGrass1Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGrass1Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDGrass2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDGrass2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDStone3Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDStone3Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDTree6Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDTree6Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDStoneBlockObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDStoneBlockObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlBodyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlBodyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlHeadObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlHeadObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDOrcBodyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDOrcBodyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDOrcHeadObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDOrcHeadObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDOrcWheelObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDOrcWheelObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerBodyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerBodyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerHeadObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerHeadObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerWheelObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDTruckerWheelObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDAdventureBoyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDAdventureBoyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlWheelObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCarGirlWheelObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDAdventureGirlObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDAdventureGirlObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCatObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCatObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDCuteGirlObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDCuteGirlObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDinoObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDinoObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDDogObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDDogObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDFlatBoyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDFlatBoyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDJackObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDJackObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDKnightObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDKnightObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDKunaiObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDKunaiObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDKunai2Objects1.length = 0;
gdjs.Untitled_32sceneCode.GDKunai2Objects2.length = 0;
gdjs.Untitled_32sceneCode.GDNinjaBoyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDNinjaBoyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDNinjaGirlObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDNinjaGirlObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDRedHatBoyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDRedHatBoyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDSantaObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDSantaObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDZombieBoyObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDZombieBoyObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDZombieGirlObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDZombieGirlObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDRobotObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDRobotObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDBulletObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDBulletObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDMuzzleObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDMuzzleObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDNewSpriteObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDNewSpriteObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDRockHeadObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDRockHeadObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDtrggerObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDtrggerObjects2.length = 0;
gdjs.Untitled_32sceneCode.GDbafObjects1.length = 0;
gdjs.Untitled_32sceneCode.GDbafObjects2.length = 0;

gdjs.Untitled_32sceneCode.eventsList0(runtimeScene);

return;

}

gdjs['Untitled_32sceneCode'] = gdjs.Untitled_32sceneCode;
